name: Lint

on: push

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check linting
        run: yarn lint
