name: Prettier

on: push

jobs:
  build:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check formatting
        run: yarn prettier:check
